name: Automatisation des tests
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Compilation
        run: |
          last_directory=$(basename ${{ runner.workspace }})
          git clone https://github.com/Dablo974/Atelier_CMAKE.git
          cd ./$last_directory
          mkdir build
          cd build
          cmake ..
          make
          make test

  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction add
        run: |
          # ...compilation steps...
          ./src/calculator add 10 5

  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction sub
        run: |
          # ...compilation steps...
          ./src/calculator sub 10 5
  
  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction mul
        run: |
          # ...compilation steps...
          ./src/calculator mul 10 5
  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction div
        run: |
          # ...compilation steps...
          ./src/calculator div 10 5


  Test_Care:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction care
        run: |
          # ...compilation steps...
          ./src/calculator care 10