name: Automatisation des tests
on: push
jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Run CTest
        run: |
          cd build
          ctest --output-on-failure

  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Test fonction add
        run: |
          ./build/src/calculator add 10 5

  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Test fonction sub
        run: |
          ./build/src/calculator sub 10 5

  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Test fonction mul
        run: |
          ./build/src/calculator mul 10 5

  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Test fonction div
        run: |
          ./build/src/calculator div 10 5

  Test_Care:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure and build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: Test fonction care
        run: |
          ./build/src/calculator car 5

  Deploy:
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div, Test_Care]
    steps:
      - name: Deploy
        run: echo "Déploiement de la solution"

  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction add
        run: |
          # ...compilation steps...
          ./src/calculator add 10 5

  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction sub
        run: |
          # ...compilation steps...
          ./src/calculator sub 10 5
  
  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction mul
        run: |
          # ...compilation steps...
          ./src/calculator mul 10 5
  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction div
        run: |
          # ...compilation steps...
          ./src/calculator div 10 5


  Test_Care:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Test fonction care
        run: |
          # ...compilation steps...
          ./src/calculator care 10